//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Ride")]
pub struct Model {
    #[sea_orm(column_name = "rideID", primary_key, auto_increment = false)]
    pub ride_id: String,
    pub name: String,
    pub r#type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub opening: Time,
    pub closing: Option<Time>,
    pub pictures: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
