//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Broadcast")]
pub struct Model {
    #[sea_orm(column_name = "broadcastID", primary_key, auto_increment = false)]
    pub broadcast_id: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub recepients: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
