//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ChatRoom")]
pub struct Model {
    #[sea_orm(column_name = "roomID", primary_key, auto_increment = false)]
    pub room_id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_room_detail::Entity")]
    ChatRoomDetail,
    #[sea_orm(has_many = "super::message::Entity")]
    Message,
}

impl Related<super::chat_room_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoomDetail.def()
    }
}

impl Related<super::message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Message.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::chat_room_detail::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::chat_room_detail::Relation::ChatRoom.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
