//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "LostItem")]
pub struct Model {
    #[sea_orm(column_name = "itemID", primary_key, auto_increment = false)]
    pub item_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub image: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_name = "lastSeen", column_type = "Text")]
    pub last_seen: String,
    pub color: Option<String>,
    pub status: Option<String>,
    #[sea_orm(column_name = "foundAt", column_type = "Text", nullable)]
    pub found_at: Option<String>,
    #[sea_orm(column_name = "finderID")]
    pub finder_id: Option<String>,
    #[sea_orm(column_name = "ownerID")]
    pub owner_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::FinderId",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::OwnerId",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User1,
}

impl ActiveModelBehavior for ActiveModel {}
