//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "MaintenanceJobAllocation")]
pub struct Model {
    #[sea_orm(column_name = "jobID")]
    pub job_id: String,
    #[sea_orm(column_name = "staffID", primary_key, auto_increment = false)]
    pub staff_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maintenance_job::Entity",
        from = "Column::JobId",
        to = "super::maintenance_job::Column::JobId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MaintenanceJob,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Staff,
}

impl Related<super::maintenance_job::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MaintenanceJob.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
