//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Menu")]
pub struct Model {
    #[sea_orm(column_name = "menuID", primary_key, auto_increment = false)]
    pub menu_id: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Float")]
    pub price: f32,
    pub pictures: Option<Vec<String>>,
    #[sea_orm(column_name = "restaurantID")]
    pub restaurant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_detail::Entity")]
    OrderDetail,
    #[sea_orm(
        belongs_to = "super::restaurant::Entity",
        from = "Column::RestaurantId",
        to = "super::restaurant::Column::RestaurantId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Restaurant,
}

impl Related<super::order_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderDetail.def()
    }
}

impl Related<super::restaurant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Restaurant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
