//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;
use chrono::NaiveDateTime;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "Message")]
pub struct Model {
    #[sea_orm(column_name = "messageID", primary_key, auto_increment = false)]
    pub message_id: String,
    #[sea_orm(column_name = "senderID")]
    pub sender_id: String,
    #[sea_orm(column_name = "roomID")]
    pub room_id: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub timestamp: NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chat_room::Entity",
        from = "Column::RoomId",
        to = "super::chat_room::Column::RoomId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChatRoom,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::SenderId",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::chat_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoom.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
