//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Order")]
pub struct Model {
    #[sea_orm(column_name = "orderID", primary_key, auto_increment = false)]
    pub order_id: String,
    #[sea_orm(column_name = "restaurantID")]
    pub restaurant_id: String,
    #[sea_orm(column_name = "customerID")]
    pub customer_id: String,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_detail::Entity")]
    OrderDetail,
    #[sea_orm(
        belongs_to = "super::restaurant::Entity",
        from = "Column::RestaurantId",
        to = "super::restaurant::Column::RestaurantId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Restaurant,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CustomerId",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::order_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderDetail.def()
    }
}

impl Related<super::restaurant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Restaurant.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
