//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::broadcast::Entity as Broadcast;
pub use super::chat_room::Entity as ChatRoom;
pub use super::chat_room_detail::Entity as ChatRoomDetail;
pub use super::customer::Entity as Customer;
pub use super::division::Entity as Division;
pub use super::lost_item::Entity as LostItem;
pub use super::maintenance_job::Entity as MaintenanceJob;
pub use super::menu::Entity as Menu;
pub use super::message::Entity as Message;
pub use super::notification::Entity as Notification;
pub use super::order::Entity as Order;
pub use super::order_detail::Entity as OrderDetail;
pub use super::proposal::Entity as Proposal;
pub use super::queue::Entity as Queue;
pub use super::restaurant::Entity as Restaurant;
pub use super::restaurant_staff_allocation::Entity as RestaurantStaffAllocation;
pub use super::ride::Entity as Ride;
pub use super::ride_staff_allocation::Entity as RideStaffAllocation;
pub use super::sales_associate_allocation::Entity as SalesAssociateAllocation;
pub use super::souvenir::Entity as Souvenir;
pub use super::staff::Entity as Staff;
pub use super::store::Entity as Store;
pub use super::transaction::Entity as Transaction;
pub use super::transaction_detail::Entity as TransactionDetail;
pub use super::user::Entity as User;
