//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Proposal")]
pub struct Model {
    #[sea_orm(column_name = "proposalID", primary_key, auto_increment = false)]
    pub proposal_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub recepient: String,
    pub subject: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Text")]
    pub response: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
