//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Restaurant")]
pub struct Model {
    #[sea_orm(column_name = "restaurantID", primary_key, auto_increment = false)]
    pub restaurant_id: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub cuisine: String,
    pub pictures: Option<Vec<String>>,
    pub opening: Time,
    pub closing: Time,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::menu::Entity")]
    Menu,
    #[sea_orm(has_many = "super::order::Entity")]
    Order,
    #[sea_orm(has_many = "super::restaurant_staff_allocation::Entity")]
    RestaurantStaffAllocation,
}

impl Related<super::menu::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Menu.def()
    }
}

impl Related<super::order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Order.def()
    }
}

impl Related<super::restaurant_staff_allocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantStaffAllocation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
