//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "RideStaffAllocation")]
pub struct Model {
    #[sea_orm(column_name = "staffID", primary_key, auto_increment = false)]
    pub staff_id: String,
    #[sea_orm(column_name = "rideID")]
    pub ride_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ride::Entity",
        from = "Column::RideId",
        to = "super::ride::Column::RideId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Ride,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::StaffId",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::ride::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ride.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
