//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Souvenir")]
pub struct Model {
    #[sea_orm(column_name = "souvenirID", primary_key, auto_increment = false)]
    pub souvenir_id: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub pictures: Option<Vec<String>>,
    #[sea_orm(column_type = "Float")]
    pub price: f32,
    #[sea_orm(column_name = "storeID")]
    pub store_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::store::Entity",
        from = "Column::StoreId",
        to = "super::store::Column::StoreId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Store,
    #[sea_orm(has_many = "super::transaction_detail::Entity")]
    TransactionDetail,
}

impl Related<super::store::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl Related<super::transaction_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionDetail.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        super::transaction_detail::Relation::Transaction.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::transaction_detail::Relation::Souvenir.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
