//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "Staff")]
pub struct Model {
    #[sea_orm(column_name = "userID", primary_key, auto_increment = false)]
    pub user_id: String,
    #[sea_orm(column_name = "divisionID")]
    pub division_id: String,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::division::Entity",
        from = "Column::DivisionId",
        to = "super::division::Column::DivisionId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Division,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::division::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Division.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
