//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Store")]
pub struct Model {
    #[sea_orm(column_name = "storeID", primary_key, auto_increment = false)]
    pub store_id: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub pictures: Option<Vec<String>>,
    pub opening: Option<Time>,
    pub closing: Option<Time>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::souvenir::Entity")]
    Souvenir,
    #[sea_orm(has_many = "super::transaction::Entity")]
    Transaction,
}

impl Related<super::souvenir::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Souvenir.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
