//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Transaction")]
pub struct Model {
    #[sea_orm(column_name = "transactionID", primary_key, auto_increment = false)]
    pub transaction_id: String,
    #[sea_orm(column_name = "customerID")]
    pub customer_id: String,
    #[sea_orm(column_name = "storeID")]
    pub store_id: String,
    pub time: Date,
    pub status: String,
    pub payment: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::store::Entity",
        from = "Column::StoreId",
        to = "super::store::Column::StoreId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Store,
    #[sea_orm(has_many = "super::transaction_detail::Entity")]
    TransactionDetail,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CustomerId",
        to = "super::user::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::store::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl Related<super::transaction_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionDetail.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::souvenir::Entity> for Entity {
    fn to() -> RelationDef {
        super::transaction_detail::Relation::Souvenir.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::transaction_detail::Relation::Transaction.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
