//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "TransactionDetail")]
pub struct Model {
    #[sea_orm(column_name = "transactionID", primary_key, auto_increment = false)]
    pub transaction_id: String,
    #[sea_orm(column_name = "souvenirID", primary_key, auto_increment = false)]
    pub souvenir_id: String,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::souvenir::Entity",
        from = "Column::SouvenirId",
        to = "super::souvenir::Column::SouvenirId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Souvenir,
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::TransactionId",
        to = "super::transaction::Column::TransactionId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transaction,
}

impl Related<super::souvenir::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Souvenir.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
