//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Serialize)]
#[sea_orm(table_name = "User")]
pub struct Model {
    #[sea_orm(column_name = "userID", primary_key, auto_increment = false)]
    pub user_id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub password: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_room_detail::Entity")]
    ChatRoomDetail,
    #[sea_orm(has_many = "super::customer::Entity")]
    Customer,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::order::Entity")]
    Order,
    #[sea_orm(has_many = "super::queue::Entity")]
    Queue,
    #[sea_orm(has_one = "super::restaurant_staff_allocation::Entity")]
    RestaurantStaffAllocation,
    #[sea_orm(has_one = "super::ride_staff_allocation::Entity")]
    RideStaffAllocation,
    #[sea_orm(has_one = "super::sales_associate_allocation::Entity")]
    SalesAssociateAllocation,
    #[sea_orm(has_many = "super::staff::Entity")]
    Staff,
    #[sea_orm(has_many = "super::transaction::Entity")]
    Transaction,
    #[sea_orm(has_many = "super::message::Entity")]
    Message,
}

impl Related<super::chat_room_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoomDetail.def()
    }
}

impl Related<super::customer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customer.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Order.def()
    }
}

impl Related<super::queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Queue.def()
    }
}

impl Related<super::restaurant_staff_allocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantStaffAllocation.def()
    }
}

impl Related<super::ride_staff_allocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideStaffAllocation.def()
    }
}

impl Related<super::sales_associate_allocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalesAssociateAllocation.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl Related<super::message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Message.def()
    }
}

impl Related<super::chat_room::Entity> for Entity {
    fn to() -> RelationDef {
        super::chat_room_detail::Relation::ChatRoom.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::chat_room_detail::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
